create table if not exists public.keepalive_pings (
  id bigint generated by default as identity primary key,
  source text not null default 'dashboard',
  created_at timestamptz not null default now()
);

alter table public.keepalive_pings enable row level security;

drop policy if exists "Allow insert keepalive pings" on public.keepalive_pings;

create policy "Allow insert keepalive pings"
on public.keepalive_pings
for insert
to anon, authenticated
with check (true);