create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  reservation_name text not null,
  guest_name text not null,
  passes_assigned integer not null default 1,
  attendance_status text not null check (attendance_status in ('si', 'no')),
  companions_confirmed integer not null default 0,
  contact_phone text,
  notes text,
  responded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reservation_name, guest_name)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_rsvp_updated_at on public.rsvp_responses;
create trigger trg_rsvp_updated_at
before update on public.rsvp_responses
for each row
execute function public.set_updated_at();

alter table public.rsvp_responses enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on table public.rsvp_responses to anon, authenticated;
grant usage, select on sequence public.rsvp_responses_id_seq to anon, authenticated;

drop policy if exists "allow_insert_rsvp" on public.rsvp_responses;
drop policy if exists "allow_update_rsvp" on public.rsvp_responses;
drop policy if exists "allow_select_rsvp" on public.rsvp_responses;

create policy "allow_insert_rsvp"
on public.rsvp_responses
for insert
to anon
with check (true);

create policy "allow_update_rsvp"
on public.rsvp_responses
for update
to anon
using (true)
with check (true);

create policy "allow_select_rsvp"
on public.rsvp_responses
for select
to anon
using (true);
